[package]
name = "not_mario_server"
version = "0.1.0"
authors = ["Andrea Cavalli <andrea@warp.ovh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
